# Generated by Django 3.2 on 2021-04-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210412_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Post_Image/')),
                ('Caption', models.TextField()),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userrecord')),
            ],
        ),
    ]
