# Generated by Django 3.2 on 2021-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='Email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
