# Generated by Django 3.2 on 2021-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userrecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='Gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
