# Generated by Django 3.2 on 2021-04-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210424_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
