# Generated by Django 3.2 on 2021-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userrecord_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='profile_pic',
            field=models.ImageField(default='static/app/images/ZZ5H.gif', upload_to='photo/'),
        ),
    ]
